version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.94.0
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  crawl4ai:
    image: unclecode/crawl4ai:all-arm64
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=12345
    restart: unless-stopped

volumes:
  n8n_data: